export const GlobalStylesTheme = {
  black: '#000',
  bodyBg: '#fff',
  bodyColour: '#212529',
  danger: '#dc3545',
  dark: '#343a40',
  dtFontWeight: '700',
  fontFamilyBase: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  fontFamilyMonospace: 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  fontSizeBase: '1rem',
  fontWeightBase: '400',
  fontWeightBolder: 'bolder',
  gridColumns: '12',
  gridGutter: '1rem',
  headingsColour: 'inherit',
  headingsFontFamily: 'inherit',
  headingsLineHeight: '1.2',
  headingsMarginBottom: '.5rem',
  headingsFontWeight: '500',
  h1FontSize: '2.5rem',
  h2FontSize: '2rem',
  h3FontSize: '1.75rem',
  h4FontSize: '1.5rem',
  h5FontSize: '1.25rem',
  h6FontSize: '1rem',
  info: '#17a2b8',
  labelMarginBottom: '.5rem',
  leadFontSize: '1.25rem',
  leadFontWeight: '300',
  light: '#f8f9fa',
  lineHeightBase: '1.5',
  linkColour: '#007bff',
  linkDecoration: 'none',
  linkHoverColour: '#0056b3',
  linkHoverDecoration: 'underline',
  paragraphsMarginBottom: '1rem',
  primary: '#007bff',
  secondary: '#6c757d',
  success: '#28a745',
  tableCaptionColour: '#6c757d',
  tableCellPadding: '0.75rem',
  warning: '#ffc107',
  white: '#fff',
  zIndexBackdrop: '1000',
  zIndexSpinner: '1100'
};
